# Generated by Django 4.2.16 on 2024-10-10 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('type', models.CharField(choices=[('MC', 'MultiChoice'), ('NM', 'Numeric'), ('TX', 'Text')], max_length=2)),
                ('text', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('explanation', models.CharField(blank=True, default=None, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MultiChoiceAnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_graded', models.BooleanField(default=True)),
                ('title', models.CharField(default='Untitled Quiz', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.quiz')),
                ('responder', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MultiChoiceQuestion',
            fields=[
                ('basequestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.basequestion')),
                ('is_single_answer', models.BooleanField(default=True)),
            ],
            bases=('mainapp.basequestion',),
        ),
        migrations.CreateModel(
            name='NumericQuestion',
            fields=[
                ('basequestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.basequestion')),
                ('correct_answer', models.FloatField()),
                ('error_margin', models.FloatField()),
            ],
            bases=('mainapp.basequestion',),
        ),
        migrations.CreateModel(
            name='TextQuestion',
            fields=[
                ('basequestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.basequestion')),
                ('is_case_sensitive', models.BooleanField(default=True)),
                ('max_characters', models.IntegerField()),
            ],
            bases=('mainapp.basequestion',),
        ),
        migrations.AddField(
            model_name='basequestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.quiz'),
        ),
        migrations.CreateModel(
            name='TextQuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=150)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.quizresponse')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.textquestion')),
            ],
        ),
        migrations.CreateModel(
            name='TextAnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.textquestion')),
            ],
        ),
        migrations.CreateModel(
            name='NumericQuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.FloatField()),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.quizresponse')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.numericquestion')),
            ],
        ),
        migrations.CreateModel(
            name='MultiChoiceQuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.multichoiceansweroption')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.quizresponse')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.multichoicequestion')),
            ],
        ),
        migrations.AddField(
            model_name='multichoiceansweroption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.multichoicequestion'),
        ),
    ]
