# Generated by Django 5.1.2 on 2024-10-11 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basequestion',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='textquestion',
            name='basequestion_ptr',
        ),
        migrations.RemoveField(
            model_name='numericquestion',
            name='basequestion_ptr',
        ),
        migrations.RemoveField(
            model_name='numericquestionresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='numericquestionresponse',
            name='response',
        ),
        migrations.RemoveField(
            model_name='textansweroption',
            name='question',
        ),
        migrations.RemoveField(
            model_name='textquestionresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='textquestionresponse',
            name='response',
        ),
        migrations.RenameModel(
            old_name='MultiChoiceAnswerOption',
            new_name='AnswerOption',
        ),
        migrations.RenameModel(
            old_name='MultiChoiceQuestionResponse',
            new_name='QuestionResponse',
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RB', 'Radio Buttons'), ('CB', 'Checkbox')], max_length=2)),
                ('text', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('explanation', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.quiz')),
            ],
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.question'),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.question'),
        ),
        migrations.DeleteModel(
            name='MultiChoiceQuestion',
        ),
        migrations.DeleteModel(
            name='BaseQuestion',
        ),
        migrations.DeleteModel(
            name='NumericQuestion',
        ),
        migrations.DeleteModel(
            name='NumericQuestionResponse',
        ),
        migrations.DeleteModel(
            name='TextAnswerOption',
        ),
        migrations.DeleteModel(
            name='TextQuestion',
        ),
        migrations.DeleteModel(
            name='TextQuestionResponse',
        ),
    ]
