# Generated by Django 5.1.2 on 2024-10-12 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_basequestion_quiz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='is_graded',
        ),
    ]
