# Generated by Django 5.1.2 on 2024-10-13 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_quiz_is_graded'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizresponse',
            old_name='datetime',
            new_name='submitted_at',
        ),
        migrations.AlterField(
            model_name='quizresponse',
            name='responder',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LiveQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('access', models.CharField(choices=[('PUB', 'Public'), ('PRT', 'Password-protected'), ('PRV', 'Private')], default='PUB', max_length=3)),
                ('password', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mainapp.quiz')),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='live',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mainapp.livequiz'),
        ),
        migrations.AlterField(
            model_name='quizresponse',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.livequiz'),
        ),
    ]
