# Generated by Django 5.1.2 on 2024-10-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_rename_datetime_quizresponse_submitted_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizresponse',
            old_name='quiz',
            new_name='live',
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('RB', 'Radio Buttons'), ('CB', 'Checkboxes')], default='RB', max_length=2),
        ),
    ]
