# Generated by Django 5.1.2 on 2024-10-19 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_rename_quiz_quizresponse_live_alter_question_type'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='question',
            order_with_respect_to='quiz',
        ),
    ]
